# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/

default_job = "check"

[jobs.check]
command = ["cargo", "check", "--workspace", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--workspace", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--workspace",
  "--all-targets",
  "--color",
  "always",
]
need_stdout = false

[jobs.test]
command = [
  "cargo",
  "test",
  "--workspace",
  "--color",
  "always",
  "--",
  "--color",
  "always",
]
need_stdout = true
default_watch = false
watch = ["crates"]

[jobs.doc]
command = ["cargo", "doc", "--workspace", "--color", "always", "--no-deps"]
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--color", "always", "-p", "wayfind_cli"]
need_stdout = true
allow_warnings = true

[keybindings]
j = "scroll-lines(1)"
k = "scroll-lines(-1)"
ctrl-d = "scroll-pages(1)"
ctrl-u = "scroll-pages(-1)"
g = "scroll-to-top"
shift-g = "scroll-to-bottom"
