//! Git hook lifecycle for the lint pipeline.
//!
//! One hook is managed: `pre-commit`. It delegates to
//! `cargo run -p xtask -- lint --staged-only`, so the hook script never has to
//! change when a check is added or removed.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use color_eyre::eyre::{eyre, Result};

/// Every hook this task owns.
const HOOKS: &[&str] = &["pre-commit"];

/// The hook script. It is deliberately tiny: the decisions live in Rust.
const PRE_COMMIT_SCRIPT: &str = "\
#!/bin/sh
# Generated by: cargo run -p xtask -- lint --install-hooks
exec cargo run -p xtask -- lint --staged-only
";

/// The directory the task runs from, which must be the workspace root.
fn project_root() -> Result<PathBuf> {
    Ok(env::current_dir()?)
}

/// Refuse to touch `.git/hooks` when there is no repository.
fn check_git_repo(root: &Path) -> Result<()> {
    if !root.join(".git").exists() {
        return Err(eyre!("not a git repository; run from the workspace root"));
    }
    Ok(())
}

/// Write the hook, keeping a timestamped copy of anything already there.
pub fn install_hooks() -> Result<()> {
    let root = project_root()?;
    check_git_repo(&root)?;

    let hooks_dir = root.join(".git").join("hooks");
    fs::create_dir_all(&hooks_dir)?;

    for hook in HOOKS {
        let hook_path = hooks_dir.join(hook);

        // A hand-written hook is somebody's work. Move it aside, never delete it.
        if hook_path.exists() && !hook_path.is_symlink() {
            let stamp = chrono::Local::now().format("%Y%m%d_%H%M%S");
            let backup = hook_path.with_extension(format!("backup.{stamp}"));
            fs::rename(&hook_path, &backup)?;
            println!("backed up existing {hook} -> {}", backup.display());
        }

        fs::write(&hook_path, PRE_COMMIT_SCRIPT)?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&hook_path, fs::Permissions::from_mode(0o755))?;
        }

        println!("installed {hook} hook");
    }
    Ok(())
}

/// Remove the hook. A missing hook is reported, not an error.
pub fn uninstall_hooks() -> Result<()> {
    let root = project_root()?;
    check_git_repo(&root)?;

    let hooks_dir = root.join(".git").join("hooks");

    for hook in HOOKS {
        let hook_path = hooks_dir.join(hook);
        if hook_path.exists() {
            fs::remove_file(&hook_path)?;
            println!("removed {hook} hook");
        } else {
            println!("no {hook} hook found");
        }
    }
    Ok(())
}

/// Report which hooks are in place.
pub fn show_status() -> Result<()> {
    let root = project_root()?;
    check_git_repo(&root)?;

    let hooks_dir = root.join(".git").join("hooks");

    for hook in HOOKS {
        let hook_path = hooks_dir.join(hook);
        let status = if hook_path.exists() {
            "installed"
        } else {
            "not installed"
        };
        println!("{hook}: {status}");
    }
    Ok(())
}
